config/routes.rb
DiseasesMap::Application.routes.draw do
  resources :locations

  resources :diseases

end

app/models/disease.rb
class Disease < ActiveRecord::Base
  attr_accessible :code, :description, :name
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city, :country, :latitude, :longitude, :neighborhood, :number, :state, :street
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  # GET /diseases
  # GET /diseases.json
  def index
    @diseases = Disease.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diseases }
    end
  end

  # GET /diseases/1
  # GET /diseases/1.json
  def show
    @disease = Disease.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @disease }
    end
  end

  # GET /diseases/new
  # GET /diseases/new.json
  def new
    @disease = Disease.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @disease }
    end
  end

  # GET /diseases/1/edit
  def edit
    @disease = Disease.find(params[:id])
  end

  # POST /diseases
  # POST /diseases.json
  def create
    @disease = Disease.new(params[:disease])

    respond_to do |format|
      if @disease.save
        format.html { redirect_to @disease, notice: 'Disease was successfully created.' }
        format.json { render json: @disease, status: :created, location: @disease }
      else
        format.html { render action: "new" }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diseases/1
  # PUT /diseases/1.json
  def update
    @disease = Disease.find(params[:id])

    respond_to do |format|
      if @disease.update_attributes(params[:disease])
        format.html { redirect_to @disease, notice: 'Disease was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diseases/1
  # DELETE /diseases/1.json
  def destroy
    @disease = Disease.find(params[:id])
    @disease.destroy

    respond_to do |format|
      format.html { redirect_to diseases_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/diseases/_form.html.erb
<%= form_for(@disease) do |f| %>
  <% if @disease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disease.errors.count, "error") %> prohibited this disease from being saved:</h2>

      <ul>
      <% @disease.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diseases/edit.html.erb
<h1>Editing disease</h1>

<%= render 'form' %>

<%= link_to 'Show', @disease %> |
<%= link_to 'Back', diseases_path %>

app/views/diseases/index.html.erb
<h1>Listing diseases</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diseases.each do |disease| %>
  <tr>
    <td><%= disease.code %></td>
    <td><%= disease.name %></td>
    <td><%= disease.description %></td>
    <td><%= link_to 'Show', disease %></td>
    <td><%= link_to 'Edit', edit_disease_path(disease) %></td>
    <td><%= link_to 'Destroy', disease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Disease', new_disease_path %>

app/views/diseases/new.html.erb
<h1>New disease</h1>

<%= render 'form' %>

<%= link_to 'Back', diseases_path %>

app/views/diseases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @disease.code %>
</p>

<p>
  <b>Name:</b>
  <%= @disease.name %>
</p>

<p>
  <b>Description:</b>
  <%= @disease.description %>
</p>


<%= link_to 'Edit', edit_disease_path(@disease) %> |
<%= link_to 'Back', diseases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiseasesMap</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :neighborhood %><br />
    <%= f.text_field :neighborhood %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Street</th>
    <th>Number</th>
    <th>Neighborhood</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.street %></td>
    <td><%= location.number %></td>
    <td><%= location.neighborhood %></td>
    <td><%= location.city %></td>
    <td><%= location.state %></td>
    <td><%= location.country %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<div id="request">
    <p>Fields with "*" are required.<p>
    <table>
        <tr>
            <td>* Origin:</td>
            <td><input type="text" id="origin" name="origin"></td>
            <td>(Curitiba) (Rua 15 de Novembro, 1000, Curitiba)</td>
        </tr>
        <tr>
            <td>Intermediates (separete by "#"):</td>
            <td><input type="text" id="intermediates" name="intermediates"></td>
            <td>(São Paulo # Rio de Janeiro) (Rua 7 de Setembro, 4848, Curitiba # Rua 24 de Maio, 234, Curitiba)</td>
        </tr>
        <tr>
            <td>* Destination:</td>
            <td><input type="text" id="destination" name="destination"></td>
            <td>(Manaus) (Rua Mariano Torres, 146, Curitiba)</td>
        </tr>
        <tr>
            <td>Travel Mode:</td>
            <td><input type="text" id="travel_mode" name="travel_mode"></td>
            <td>(DRIVING) (BICYCLING) (TRANSIT) (WALKING)</td>
        </tr>
        <tr>
            <td>Direction Color:</td>
            <td><input type="text" id="direction_color" name="direction_color"></td>
            <td>(red) (green)</td>
        </tr>
        <tr>
            <td><button id="generateRoute">Generate Route</button></td>
            <td><button id="clearDirectionsOfMap">Clear Directions Of Map</button></td>
            <td></td>
        </tr>
    </table>

</div>

<br />

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<div id="directions_panel" style="margin:20px;background-color:#FFEE77;"></div>

<br />
<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Street:</b>
  <%= @location.street %>
</p>

<p>
  <b>Number:</b>
  <%= @location.number %>
</p>

<p>
  <b>Neighborhood:</b>
  <%= @location.neighborhood %>
</p>

<p>
  <b>City:</b>
  <%= @location.city %>
</p>

<p>
  <b>State:</b>
  <%= @location.state %>
</p>

<p>
  <b>Country:</b>
  <%= @location.country %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>